// <auto-generated />
namespace Service.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Confused : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Confused));
        
        string IMigrationMetadata.Id
        {
            get { return "201412061941193_Confused"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
